### ISSUE TITLE
do you have this for latest vuejs version??

### ISSUE THREAD

**Issue by jujusudhur** [Nayir/WueJS---Wordpress-Starter-Theme#1]

**Comment by Nayir** [comment]
Yes, but not finished yet. I changed the way of routes are working. VueRouter is great, but probably a bad idea for developing on Wordpress when you want to use the WP functions.

If you want to use VueRouter, the best way is load the data from the REST API and using it on another website in fullJS.

Then I started a hybrid Wordpress Starter Theme, not using VueRouter anymore. But still using the power of Vuejs and REST API.

Next release : may or june 2017
